server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http:/localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
#      client:
#        registration:
#          gateway:
#            provider: oauth
#            client-id: qrdata
#            client-secret: scrts
#            authorization-grant-type: client_credentials
#        provider:
#          oauth:
#            token-uri: https://localhost:9000
#            jwk-set-uri: http://localhost:9000/oauth2/jwks
  cloud:
    gateway:
      routes:
        - id: car
          uri: http://localhost:9010/
          predicates:
            - Path=/api/**
        - id: oauth
          uri: http://localhost:9000/
          predicates:
            - Path=/oauth/**
        - id: qr-data
          uri: http://localhost:2023/
          predicates:
            - Path=/acquire/**
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.web.HttpLogging: info
    org.springframework.security: info
    org.springframework.security.oauth2: trace
    org.springframework.cloud.gateway: info